<!DOCTYPE html>
<html lang="en"><head>
<script src="Aula 8_files/libs/clipboard/clipboard.min.js"></script>
<script src="Aula 8_files/libs/quarto-html/tabby.min.js"></script>
<script src="Aula 8_files/libs/quarto-html/popper.min.js"></script>
<script src="Aula 8_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Aula 8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Aula 8_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Aula 8_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <title>Introdução à economia</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Aula 8_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Aula 8_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="Aula 8_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link href="Aula 8_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Aula 8_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Aula 8_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Aula 8_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introdução à economia</h1>
  <p class="subtitle">Aula 8 - Custos de Produção</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="menu" class="slide level2 smaler scrollable">
<h2>Consumidores, Produtores e a eficiência do mercado</h2>
<h3 id="introdução">Introdução</h3>
<p><a href="#/intro">01 — Introdução</a></p>
<h3 id="o-que-são-custos">O que são custos?</h3>
<p><a href="#/rtctprof">02 — Receita Total, Custo Total e Lucro</a></p>
<p><a href="#/cuscusop">03 — Custos como custos de oportunidade</a></p>
<p><a href="#/#cuscapcusop">04 — Custo do capital como custo de oportunidade</a></p>
<p><a href="#/lucrecolucroco">05 — Lucro econômico versus lucro contábil</a></p>
<p><a href="#/JRP1">🏆 Vamos a um Jogo rápido!</a></p>
<h3 id="produção-e-custos">Produção e custos</h3>
<p><a href="#/funpro">06 — A função de produção</a></p>
<p><a href="#/prodcus">07 — Da produção aos custos</a></p>
<p><a href="#/JRP2">🏆 Vamos a um Jogo rápido!</a></p>
<h3 id="as-várias-medidas-de-custo">As várias medidas de custo</h3>
<p><a href="#/custos">08 — Custo total, fixo, variável, médio e marginal</a></p>
<p><a href="#/curcusfor">09 - Curva de custos e suas formas</a></p>
<p><a href="#/JRP3">🏆 Vamos a um Jogo rápido!</a></p>
<h3 id="custos-no-curto-e-longo-prazo">Custos no curto e longo prazo</h3>
<p><a href="#/reltempcust">10 — A relação entre curto prazo, longo prazo e o custo médio total</a></p>
<p><a href="#/ecodesecoesc">11 — Economias e deseconomias de escala</a></p>
<p><a href="#/JRP4">🏆 Vamos a um Jogo rápido!</a></p>
<h3 id="conclusão">Conclusão</h3>
<p><a href="#/conclusao">Conclusão: Eficiência de mercado e falhas de mercado</a></p>
</section>
<section id="intro" class="slide level2 smaller scrollable">
<h2>Introdução</h2>
<p>Até agora, tratamos a curva de oferta como dada:</p>
<p>Preço ↑ → Quantidade ofertada ↑</p>
<p>Mas o que determina quanto uma empresa decide produzir?</p>
<p>A partir de agora, vamos olhar para dentro da firma:</p>
<p>💰 Quanto custa produzir? 🏭 Quanto produzir? 💵 A que preço vender? 📈 Como maximizar o lucro? 🏪 Como essas decisões mudam conforme o mercado?</p>
<p>🔑 O ponto de partida: <strong>custos de produção</strong></p>
<p>Os custos são fundamentais para entender as decisões de produção, oferta e preço das empresas.</p>
<p><strong>Este capítulo constrói a base para estudarmos a Organização Industrial:</strong></p>
<p>como o comportamento das firmas depende das condições de mercado.</p>
<p><a href="#/menu">← Menu</a></p>
</section>
<section id="rtctprof" class="slide level2 smaller scrollable">
<h2>02 — Receita Total, Custo Total e Lucro]</h2>
<p><img src="imagens/img_0.png" style="width: 900px; height: auto;"></p>
<p>Para entender as decisões de uma empresa, precisamos começar por uma pergunta:</p>
<p><strong>O que a firma está tentando alcançar?</strong></p>
<p>Na análise econômica, normalmente assumimos que a firma busca <strong>maximizar seu lucro</strong>.</p>
<p>📊 <strong>Receita, custo e lucro</strong></p>
<p><strong>Receita Total (RT)</strong></p>
<p>Valor recebido pela venda dos bens e serviços:</p>
<p><span class="math display">\[ RT = P \times Q \]</span></p>
<p><strong>Custo Total (CT)</strong>: Valor dos recursos utilizados para produzir.</p>
<p><strong>Lucro (π)</strong>: É a diferença entre a receita total e o custo total:</p>
<p><span class="math display">\[ \boxed{\pi = RT - CT} \]</span></p>
<p><strong>🍪 Exemplo</strong></p>
<p>Se Tia Anastácia produz 10.000 bolinhos e vende cada um por $2:</p>
<p><span class="math display">\[ RT = 10.000 \times 2 = \$20.000 \]</span></p>
<p>Calcular a receita é relativamente simples.</p>
<p>⚠️ Mas medir corretamente o <strong>custo econômico</strong> de produzir é mais complicado.</p>
<p>➡️ E é justamente aí que começa nossa análise dos custos de produção.</p>
<p><a href="#/menu">← Menu</a></p>
</section>
<section id="cuscusop" class="slide level2 scrollable">
<h2>03 - Custos como custos de oportunidade</h2>
<p><img src="imagens/img_1.png" style="width: 900px; height: auto;"></p>
<p>Lembre-se de um dos 10 Princípios da Economia:</p>
<p>O custo de alguma coisa é aquilo de que você abre mão para obtê-la.</p>
<p>Por isso, para o economista, o custo de produção inclui todos os custos de oportunidade envolvidos na atividade da firma.</p>
<p>💵 Custos explícitos</p>
<p>Exigem um desembolso monetário da empresa.</p>
<p>🥣 Ingredientes 👩‍🍳 Salários dos trabalhadores ⚡ Energia elétrica 🏠 Aluguel 🔥 Equipamentos</p>
<p>Se Tia Nastácia gastar R$ 1.000 em ingredientes, esses R$ 1.000 não poderão ser utilizados para outra finalidade.</p>
<p>⏳ Custos implícitos</p>
<p>Não envolvem pagamento, mas representam oportunidades sacrificadas.</p>
<p>Imagine que Tia Nastácia pudesse trabalhar em outro lugar ganhando:</p>
<p><span class="math display">\[ R\$30/\text{hora} \]</span></p>
<p>Ao dedicar uma hora à sua firma de quitutes, ela abre mão desses R$ 30.</p>
<p>➡️ Embora nenhum dinheiro saia do caixa, existe um custo de oportunidade de R$ 30.</p>
<p>🧮 Para o economista <span class="math display">\[ \boxed{\text{Custo Econômico} = \text{Custos Explícitos}+\text{Custos Implícitos}} \]</span></p>
<p>Economista: considera explícitos e implícitos. Contador: normalmente registra os custos explícitos, associados aos fluxos monetários.</p>
<p>Isso explica por que uma empresa pode parecer lucrativa contabilmente e, ainda assim, não ser um bom negócio do ponto de vista econômico.</p>
<p><a href="#/menu">← Menu</a></p>
</section>
<section id="cuscapcusop" class="slide level2 smaller scrollable">
<h2>04 — Custo do capital como custo de oportunidade</h2>
<p>O <strong>custo do capital</strong> também é um <strong>custo de oportunidade</strong></p>
<p><strong>Um dos custos implícitos mais importantes de uma empresa é o custo de oportunidade do dinheiro investido nela.</strong></p>
<p>🏭 Imagine que Tia Nastácia precise de R$ 300.000</p>
<p>Ela usa R$ 300.000 de suas economias para montar a empresa.</p>
<p>Mas esse dinheiro poderia estar aplicado rendendo 5% ao ano:</p>
<p><span class="math display">\[ R\$300.000\times 5\%=\boxed{R\$15.000} \]</span></p>
<p>Ao investir na empresa, ela abre mão desses R$ 15.000 por ano.</p>
<p>➡️ Não há pagamento ou saída de caixa. ➡️ Mesmo assim, para o economista, os R$ 15.000 são um custo implícito.</p>
<p>🏦 E se parte do dinheiro for emprestada?</p>
<p>Suponha agora:</p>
<p>R$ 100.000 → economias de Tia Nastácia R$ 200.000 → empréstimo bancário a 5%</p>
<p>Temos dois custos:</p>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 44%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capital</th>
<th>Custo anual</th>
<th>Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R$ 200.000 emprestados</td>
<td>R$ 10.000 de juros pagos</td>
<td><strong>Explícito</strong></td>
</tr>
<tr class="even">
<td>R$ 100.000 próprios</td>
<td>R$ 5.000 de juros não recebidos</td>
<td><strong>Implícito</strong></td>
</tr>
<tr class="odd">
<td><strong>Custo econômico do capital</strong></td>
<td><strong>R$ 15.000</strong></td>
<td><strong>Total</strong></td>
</tr>
</tbody>
</table>
<p>🧠 Economista × Contador</p>
<p>Contador: vê R$ 10.000 de custo — o dinheiro efetivamente pago ao banco.</p>
<p>Economista: vê R$ 15.000 de custo — porque considera também aquilo de que Tia Nastácia abriu mão.</p>
<p><span class="math display">\[ \boxed{\text{Custo do capital}=10.000+5.000=R\$15.000} \]</span></p>
<p>💡 Capital próprio não é capital “de graça”.</p>
<p>Ele também possui custo de oportunidade.</p>
<p><a href="#/menu">← Menu</a></p>
</section>
<section id="lucrecolucroco" class="slide level2 smaller scrollable">
<h2>05 — Lucro econômico versus lucro contábil</h2>
<p>Agora podemos voltar ao objetivo da firma:</p>
<p>Maximizar o lucro.</p>
<p>Mas economistas e contadores chegam a valores diferentes de lucro porque medem os custos de maneira diferente.</p>
<p>🧾 Lucro contábil</p>
<p>O contador considera apenas os custos explícitos:</p>
<p><span class="math display">\[ \boxed{\text{Lucro Contábil} = RT - \text{Custos Explícitos}} \]</span></p>
<p>São os gastos que efetivamente aparecem no caixa da empresa.</p>
<p>🧠 Lucro econômico</p>
<p>O economista considera todos os custos de oportunidade:</p>
<p><span class="math display">\[ \boxed{\text{Lucro Econômico} = RT-(\text{Custos Explícitos}+\text{Custos Implícitos})} \]</span></p>
<p><img src="imagens/img_2.png" style="width: 900px; height: auto;"></p>
<p>Portanto:</p>
<p><span class="math display">\[ \boxed{\text{Lucro Econômico} =\text{Lucro Contábil}-\text{Custos Implícitos}} \]</span></p>
<p>🍰 A empresa de Tia Nastácia</p>
<p>Imagine que, durante o ano:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Receita total</td>
<td style="text-align: right;">R$ 100.000</td>
</tr>
<tr class="even">
<td>Custos explícitos</td>
<td style="text-align: right;">R$ 60.000</td>
</tr>
<tr class="odd">
<td>Custos implícitos</td>
<td style="text-align: right;">R$ 25.000</td>
</tr>
</tbody>
</table>
<p>Para o contador:</p>
<p><span class="math display">\[ 100.000-60.000=\boxed{R\$40.000} \]</span></p>
<p>Para o economista:</p>
<p><span class="math display">\[ 100.000-60.000-25.000=\boxed{R\$15.000} \]</span></p>
<p>A empresa apresenta R$ 40 mil de lucro contábil, mas apenas R$ 15 mil de lucro econômico.</p>
<p>🔑 Por que o lucro econômico importa?</p>
<p>Se:</p>
<p><span class="math display">\[ \pi_E&gt;0 \]</span></p>
<p>✅ A firma cobre todos os seus custos de oportunidade e ainda gera um retorno adicional ao proprietário.</p>
<p>Se:</p>
<p><span class="math display">\[ \pi_E=0 \]</span></p>
<p>⚖️ A firma cobre exatamente todos os custos de oportunidade. Lucro econômico zero não significa que o empresário não ganha nada.</p>
<p>Se:</p>
<p><span class="math display">\[ \pi_E&lt;0 \]</span></p>
<p>⚠️ A atividade não está cobrindo todos os custos de oportunidade. Se isso persistir, o proprietário terá incentivo para abandonar a atividade e empregar seus recursos em outra alternativa.</p>
<p>💡 É por isso que, para compreender as decisões das firmas, interessa principalmente o lucro econômico, e não apenas o lucro contábil.</p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="JRP1" class="slide level2 smaller scrollable">
<h2>🏆 Vamos a um Jogo rápido!</h2>
<p>O fazendeiro McDonald dá aulas de banjo por $20 a hora. Certo dia, ele passa 10 horas plantando $100 em sementes em sua fazenda.</p>
<p>Qual foi o custo de oportunidade incorrido por McDonald?</p>
<p>Qual custo seria contabilizado por seu contador?</p>
<p>Se essas sementes produzirem uma colheita no valor de $200, McDonald terá lucro contábil? E terá lucro econômico?</p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="funpro" class="slide level2 smaller scrollable">
<h2>06 — A função de produção</h2>
<p>Agora queremos entender como os insumos utilizados pela firma determinam quanto ela consegue produzir.</p>
<p>🍪 A função de produção</p>
<p>Suponha que Tia Nastácia comece a contratar trabalhadores para sua fábrica de quitutes.</p>
<p>A função de produção mostra a relação entre a quantidade de insumos utilizada e a quantidade produzida:</p>
<p><span class="math display">\[ \boxed{\text{Insumos} \longrightarrow \text{Produção}} \]</span></p>
<p>Neste exemplo, variaremos apenas o trabalho, mantendo os demais fatores de produção constantes.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Trabalhadores</th>
<th style="text-align: right;">Produção (unidades/hora)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">140</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">155</td>
</tr>
</tbody>
</table>
<p>👷 Produto marginal do trabalho</p>
<p>Lembre-se de outro dos 10 Princípios da Economia:</p>
<p>Pessoas racionais pensam na margem.</p>
<p>O Produto Marginal do Trabalho (PMgL) mede quanto a produção aumenta quando contratamos um trabalhador adicional:</p>
<p><span class="math display">\[ \boxed{PMg_L=\frac{\Delta Q}{\Delta L}} \]</span></p>
<p>Por exemplo, com a contratação do segundo trabalhador:</p>
<p><span class="math display">\[ PMg_L=90-50=\boxed{40} \]</span></p>
<p>O segundo trabalhador acrescenta 40 unidades por hora à produção.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Trabalhador adicional</th>
<th style="text-align: right;">Produção</th>
<th style="text-align: right;">PMgL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1º</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: right;">2º</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3º</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: right;">4º</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5º</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">6º</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
<p>Observe o padrão:</p>
<p><span class="math display">\[ 50\rightarrow40\rightarrow30\rightarrow20\rightarrow10\rightarrow5 \]</span> 📉 Produto marginal decrescente</p>
<p>À medida que mais trabalhadores são contratados, cada trabalhador adicional acrescenta menos à produção.</p>
<p>Esse fenômeno é chamado de:</p>
<p><span class="math display">\[ \boxed{\text{Produto Marginal Decrescente}} \]</span></p>
<p>Por quê?</p>
<p>Imagine a cozinha de Tia Nastácia. 👩🏾‍🍳</p>
<p>Com poucos trabalhadores, há espaço, forno e utensílios suficientes. Conforme mais pessoas entram na mesma cozinha, elas precisam dividir os equipamentos, disputar espaço e acabam até atrapalhando umas às outras.</p>
<p>➡️ O capital permanece fixo, enquanto aumentamos o trabalho.</p>
<p>Por isso:</p>
<p><span class="math display">\[ L\uparrow \quad\Rightarrow\quad PMg_L\downarrow \]</span></p>
<p>📈 E o formato da função de produção?</p>
<p>A inclinação da função de produção representa o produto marginal.</p>
<p>Assim, quando o PMgL diminui:</p>
<p><span class="math display">\[ \boxed{\text{a função de produção vai ficando mais plana}} \]</span></p>
<p>Esse resultado será fundamental para entendermos, logo adiante, por que a curva de custo fica cada vez mais inclinada à medida que a produção aumenta.</p>
</section>
<section id="prodcus" class="slide level2 smaller scrollable">
<h2>07 - Da produção aos custos</h2>
<p>Agora podemos ligar a função de produção aos custos da firma.</p>
<p>Suponha que a empresa tenha:</p>
<p>🏭 Custo da fábrica: $30 por hora 👷 Custo de cada trabalhador: $10 por hora</p>
<p>Assim:</p>
<p><span class="math display">\[ \boxed{CT = 30 + 10L} \]</span></p>
<p>Se contratar 1 trabalhador:</p>
<p><span class="math display">\[ CT=30+10=\$40 \]</span></p>
<p>Com 2 trabalhadores:</p>
<p><span class="math display">\[ CT=30+20=\$50 \]</span></p>
<p>E assim por diante.</p>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Trabalhadores</th>
<th style="text-align: right;">Produção</th>
<th style="text-align: right;">Custo da fábrica</th>
<th style="text-align: right;">Custo dos trabalhadores</th>
<th style="text-align: right;">Custo total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$0</td>
<td style="text-align: right;">$30</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$10</td>
<td style="text-align: right;">$40</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$20</td>
<td style="text-align: right;">$50</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$60</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$40</td>
<td style="text-align: right;">$70</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$50</td>
<td style="text-align: right;">$80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">$30</td>
<td style="text-align: right;">$60</td>
<td style="text-align: right;">$90</td>
</tr>
</tbody>
</table>
<p>🪙 As duas faces da mesma moeda</p>
<p>A função de produção e a curva de custo total contam a mesma história, mas de perspectivas diferentes.</p>
<p>Função de produção:</p>
<p><span class="math display">\[ \text{Trabalho} \longrightarrow \text{Produção} \]</span></p>
<p>Curva de custo total:</p>
<p><span class="math display">\[ \text{Produção} \longrightarrow \text{Custo} \]</span></p>
<p>Quando há poucos trabalhadores, contratar mais um aumenta bastante a produção.</p>
<p>Mas, com a cozinha cada vez mais cheia:</p>
<p><span class="math display">\[ PMg_L\downarrow \]</span></p>
<p>Cada trabalhador adicional produz menos.</p>
<p>Para conseguir produzir mais uma unidade, portanto, a firma precisa empregar cada vez mais trabalho.</p>
<p><span class="math display">\[ \boxed{PMg_L\downarrow \quad\Longrightarrow\quad \text{custo de produzir unidades adicionais}\uparrow} \]</span> 📈 <strong>Consequência nos gráficos</strong></p>
<p><strong>Função de produção</strong> → fica mais plana porque cada trabalhador acrescenta menos produção.</p>
<p><strong>Curva de custo total</strong> → fica mais inclinada porque aumentar a produção exige cada vez mais recursos.</p>
<p>🔑 São duas faces da mesma moeda: o produto marginal decrescente explica tanto o achatamento da função de produção quanto o aumento da inclinação da curva de custo total.</p>
<p><img src="imagens/img_7.png" style="width: 900px; height: auto;"></p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="JRP2" class="slide level2 smaller scrollable">
<h2>🏆 Vamos a um Jogo rápido!</h2>
<p>A fazendeira Jones não obtém nenhuma colheita se não plantar sementes. Se plantar:</p>
<p>1 saco de sementes → produz 3 bushels de trigo 2 sacos de sementes → produz 5 bushels 3 sacos de sementes → produz 6 bushels</p>
<p>Cada saco de sementes custa $100, e as sementes são seu único custo.</p>
<ol type="a">
<li><p>Com esses dados, represente graficamente a função de produção da fazendeira.</p></li>
<li><p>Represente graficamente sua curva de custo total.</p></li>
<li><p>Explique o formato das duas curvas e sua relação.</p></li>
</ol>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="custos" class="slide level2 smaller scrollable">
<h2>08 — Custo total, fixo, variável, médio e marginal</h2>
<p>As diferentes medidas de custo</p>
<p>O Custo Total (CT) pode ser dividido em:</p>
<p><span class="math display">\[ \boxed{CT = CF + CV} \]</span> 🏢 Custo Fixo (CF): não varia com a quantidade produzida — existe mesmo quando (Q=0). ☕ Custo Variável (CV): varia conforme a quantidade produzida.</p>
<p>A partir deles, podemos calcular os custos médios:</p>
<p><span class="math display">\[ \boxed{CMeT=\frac{CT}{Q}} \qquad \boxed{CMeF=\frac{CF}{Q}} \qquad \boxed{CMeV=\frac{CV}{Q}} \]</span></p>
<p>Portanto:</p>
<p><span class="math display">\[ \boxed{CMeT=CMeF+CMeV} \]</span></p>
<p>E há uma medida especialmente importante para a decisão da firma:</p>
<p><span class="math display">\[ \boxed{CMg=\frac{\Delta CT}{\Delta Q}} \]</span></p>
<p>Custo Médio Total: quanto custa, em média, cada unidade produzida.</p>
<p>Custo Marginal: quanto o custo total aumenta ao produzir uma unidade adicional.</p>
<p>🔑 Médio olha para o custo da unidade típica; marginal olha para o custo da próxima unidade.</p>
<p>☕ <strong>As diferentes medidas de custo</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Produção (Q)</th>
<th style="text-align: right;">CT</th>
<th style="text-align: right;">CF</th>
<th style="text-align: right;">CV</th>
<th style="text-align: right;">CMeF</th>
<th style="text-align: right;">CMeV</th>
<th style="text-align: right;">CMeT</th>
<th style="text-align: right;">CMg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$0,00</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">$3,30</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$0,30</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$0,30</td>
<td style="text-align: right;">$3,30</td>
<td style="text-align: right;">$0,30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">$3,80</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$0,80</td>
<td style="text-align: right;">$1,50</td>
<td style="text-align: right;">$0,40</td>
<td style="text-align: right;">$1,90</td>
<td style="text-align: right;">$0,50</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">$4,50</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$1,50</td>
<td style="text-align: right;">$1,00</td>
<td style="text-align: right;">$0,50</td>
<td style="text-align: right;">$1,50</td>
<td style="text-align: right;">$0,70</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">$5,40</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$2,40</td>
<td style="text-align: right;">$0,75</td>
<td style="text-align: right;">$0,60</td>
<td style="text-align: right;">$1,35</td>
<td style="text-align: right;">$0,90</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">$6,50</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$3,50</td>
<td style="text-align: right;">$0,60</td>
<td style="text-align: right;">$0,70</td>
<td style="text-align: right;">$1,30</td>
<td style="text-align: right;">$1,10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">$7,80</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$4,80</td>
<td style="text-align: right;">$0,50</td>
<td style="text-align: right;">$0,80</td>
<td style="text-align: right;">$1,30</td>
<td style="text-align: right;">$1,30</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">$9,30</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$6,30</td>
<td style="text-align: right;">$0,43</td>
<td style="text-align: right;">$0,90</td>
<td style="text-align: right;">$1,33</td>
<td style="text-align: right;">$1,50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">$11,00</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$8,00</td>
<td style="text-align: right;">$0,38</td>
<td style="text-align: right;">$1,00</td>
<td style="text-align: right;">$1,38</td>
<td style="text-align: right;">$1,70</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">$12,90</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$9,90</td>
<td style="text-align: right;">$0,33</td>
<td style="text-align: right;">$1,10</td>
<td style="text-align: right;">$1,43</td>
<td style="text-align: right;">$1,90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">$15,00</td>
<td style="text-align: right;">$3,00</td>
<td style="text-align: right;">$12,00</td>
<td style="text-align: right;">$0,30</td>
<td style="text-align: right;">$1,20</td>
<td style="text-align: right;">$1,50</td>
<td style="text-align: right;">$2,10</td>
</tr>
</tbody>
</table>
<p><img src="imagens/img_3.png" style="width: 900px; height: auto;"></p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="curcusfor" class="slide level2 smaller scrollable">
<h2>09 - Curva de custos e suas formas</h2>
<p><img src="imagens/img_4.png" style="width: 900px; height: auto;"></p>
<p>Assim como as curvas de oferta e demanda nos ajudaram a analisar o comportamento dos mercados, as curvas de custo médio e custo marginal nos ajudam a compreender as decisões das firmas.</p>
<p>As principais curvas são:</p>
<p>CMeT — Custo Médio Total CMeF — Custo Médio Fixo CMeV — Custo Médio Variável CMg — Custo Marginal</p>
<p>🔺 <strong>Custo Marginal Crescente</strong></p>
<p>O CMg aumenta à medida que a produção cresce, refletindo o produto marginal decrescente.</p>
<p>Quando a produção é pequena, existem recursos ociosos e um trabalhador adicional acrescenta muito à produção:</p>
<p><span class="math display">\[ PMg_L \text{ alto} \Rightarrow CMg \text{ baixo} \]</span></p>
<p>Quando a produção é elevada, equipamentos e espaço ficam congestionados:</p>
<p><span class="math display">\[ \boxed{PMg_L\downarrow \Rightarrow CMg\uparrow} \]</span> 🟦 Custo Médio Total em forma de U</p>
<p>Como:</p>
<p><span class="math display">\[ \boxed{CMeT=CMeF+CMeV} \]</span></p>
<p>o formato do CMeT resulta de duas forças:</p>
<p>📉 <strong>CMeF diminui</strong>: o custo fixo é dividido entre um número cada vez maior de unidades.</p>
<p>📈 <strong>CMeV aumenta</strong>: devido ao produto marginal decrescente.</p>
<p>Em níveis baixos de produção, predomina a queda do CMeF, fazendo o CMeT cair. Em níveis elevados, predomina o aumento do CMeV, fazendo o CMeT subir.</p>
<p><span class="math display">\[ \boxed{\text{CMeT tem formato de U}} \]</span></p>
<p>⚙️ <strong>Escala eficiente</strong>**</p>
<p>O ponto mínimo da curva de CMeT determina a escala eficiente:</p>
<p><strong>Escala eficiente</strong>: quantidade produzida que minimiza o custo médio total.</p>
<p>No exemplo, o CMeT mínimo é de $1,30 por unidade, alcançado com uma produção de 5 ou 6 unidades por hora.</p>
<p>🔑 <strong>Três propriedades importantes</strong></p>
<p>CMg aumenta com a quantidade produzida. CMeT possui formato de U. CMg cruza o CMeT no ponto mínimo do CMeT.</p>
<p><img src="imagens/img_5.png" style="width: 900px; height: auto;"></p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="JRP3" class="slide level2 smaller scrollable">
<h2>🏆 Vamos a um Jogo rápido!</h2>
<p>Suponha que o custo total da Honda para produzir 4 carros seja $225.000 e que o custo total para produzir 5 carros seja $250.000.</p>
<ol type="a">
<li><p>Qual é o custo médio total de produzir 5 carros?</p></li>
<li><p>Qual é o custo marginal do quinto carro?</p></li>
<li><p>Desenhe as curvas de custo marginal (CMg) e custo médio total (CMeT) de uma firma típica e explique por que elas se cruzam no ponto em que se cruzam.</p></li>
</ol>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="reltempcust" class="slide level2 smaller scrollable">
<h2>10 - A relação entre curto prazo, longo prazo e o custo médio total</h2>
<p>A classificação entre custos fixos e variáveis depende do horizonte de tempo.</p>
<p>No curto prazo, algumas decisões da firma não podem ser alteradas. Uma montadora, por exemplo, pode contratar mais trabalhadores, mas não consegue construir imediatamente uma nova fábrica.</p>
<p><span class="math display">\[ \boxed{\text{Curto prazo: pelo menos um fator de produção é fixo}} \]</span></p>
<p>Assim, instalações e equipamentos podem representar custos fixos.</p>
<p>No longo prazo, a firma pode ajustar todos os fatores de produção: ampliar uma fábrica, construir outra ou fechar instalações existentes.</p>
<p><span class="math display">\[ \boxed{\text{Longo prazo: todos os fatores de produção podem ser ajustados}} \]</span></p>
<p>🏭 <strong>Curto prazo × Longo prazo</strong></p>
<p>No curto prazo, a firma está limitada pela capacidade instalada que escolheu anteriormente.</p>
<p>No longo prazo, ela pode escolher o tamanho da planta mais adequado para cada nível de produção.</p>
<p>Por isso:</p>
<p><span class="math display">\[ \boxed{CMeT_{LP}\leq CMeT_{CP}} \]</span></p>
<p>A curva de CMeT de longo prazo tende a ser mais plana e fica sobre ou abaixo das curvas de curto prazo.</p>
<p>🚗 Exemplo</p>
<p>Suponha que uma montadora queira aumentar sua produção de 1.000 para 1.200 carros por dia.</p>
<p>Curto prazo: precisa utilizar mais intensamente a fábrica existente.</p>
<p><span class="math display">\[ CMeT:\quad \$10.000\rightarrow \$12.000 \]</span></p>
<p>Longo prazo: pode ampliar a fábrica e ajustar simultaneamente capital e trabalho.</p>
<p><span class="math display">\[ CMeT:\quad \$12.000\rightarrow \$10.000 \]</span></p>
<p>➡️ A maior flexibilidade do longo prazo permite à firma escolher uma combinação de fatores mais adequada à escala de produção.</p>
<p>💡 Curto e longo prazo não são definidos por um número específico de meses ou anos. Dependem de quanto tempo a firma necessita para ajustar seus fatores de produção.</p>
<p><img src="imagens/img_6.png" style="width: 900px; height: auto;"></p>
<p><a href="#/menu">← Menu</a></p>
</section>
<section id="ecodesecoesc" class="slide level2 smaller scrollable">
<h2>11 - Economias e deseconomias de escala</h2>
<p><img src="imagens/img_6.png" style="width: 900px; height: auto;"></p>
<p>A curva de Custo Médio Total de Longo Prazo (CMeTLP) mostra como o custo por unidade varia quando a firma altera sua escala de produção.</p>
<p>📉 Economias de escala</p>
<p>Quando o aumento da produção reduz o custo médio:</p>
<p><span class="math display">\[ \boxed{Q\uparrow \Rightarrow CMeT_{LP}\downarrow} \]</span></p>
<p>O crescimento permite maior especialização dos trabalhadores, melhor utilização de equipamentos e divisão de tarefas.</p>
<p>➡️ Retornos constantes de escala</p>
<p>Quando o custo médio permanece aproximadamente constante:</p>
<p><span class="math display">\[ \boxed{Q\uparrow \Rightarrow CMeT_{LP}\text{ constante}} \]</span> 📈 Deseconomias de escala</p>
<p>Quando o crescimento da produção aumenta o custo médio:</p>
<p><span class="math display">\[ \boxed{Q\uparrow \Rightarrow CMeT_{LP}\uparrow} \]</span></p>
<p>Em organizações muito grandes, surgem problemas de coordenação, comunicação e gestão.</p>
<p>🔑 Especialização favorece as economias de escala; problemas de coordenação ajudam a explicar as deseconomias de escala.</p>
<p>📌 Estudo de Caso — Adam Smith e a Fábrica de Alfinetes</p>
<p>Em A Riqueza das Nações, Adam Smith utiliza uma fábrica de alfinetes para mostrar como a divisão do trabalho e a especialização podem aumentar enormemente a produtividade.</p>
<p>Em vez de cada trabalhador fabricar sozinho um alfinete inteiro, o processo era dividido em várias tarefas:</p>
<p>1 trabalhador → estica o arame outro → endireita outro → corta outro → faz a ponta outro → prepara e coloca a cabeça outros → fazem o acabamento e a embalagem</p>
<p>Cada trabalhador passa a se especializar em uma pequena parte do processo.</p>
<p>🔨 O resultado</p>
<p>Smith observou que uma fábrica organizada dessa maneira conseguia produzir milhares de alfinetes por trabalhador por dia.</p>
<p>Sem especialização, argumentava ele, um trabalhador isolado provavelmente produziria pouquíssimos alfinetes por dia.</p>
<p><span class="math display">\[ \boxed{ \text{Maior escala} \Rightarrow \text{Divisão do trabalho} \Rightarrow \text{Especialização} \Rightarrow \text{Maior produtividade} \Rightarrow \text{Menor custo médio} } \]</span> 💡 A lição econômica</p>
<p>Uma firma maior pode dividir o processo produtivo em tarefas especializadas que seriam inviáveis em uma produção muito pequena.</p>
<p>É um mecanismo fundamental por trás das:</p>
<p><span class="math display">\[ \boxed{\text{Economias de Escala}} \]</span></p>
<p>Mas esse processo não continua indefinidamente: depois de certo tamanho, os ganhos de especialização podem ser superados pelas dificuldades de administrar uma organização cada vez maior.</p>
<p><span class="math display">\[
\text{Especialização}
\;\xrightarrow{\;CMeT \downarrow\;}\;
\text{Economias de escala}
\qquad\Big|\qquad
\text{Coordenação}
\;\xrightarrow{\;CMeT \uparrow\;}\;
\text{Deseconomias de escala}
\]</span> <a href="#/menu">← menu</a></p>
</section>
<section id="JRP4" class="slide level2 smaller scrollable">
<h2>🏆 Vamos a um Jogo rápido!</h2>
<p>Se a Boeing produz 9 aviões por mês, seu custo total de longo prazo é de $9 milhões. Se produz 10 aviões, o custo total passa para $9,5 milhões.</p>
<p>Ela apresenta economias ou deseconomias de escala?</p>
<p><a href="#/menu">← menu</a></p>
</section>
<section id="conclusao" class="slide level2 smaller scrollable">
<h2>Conclusão: Eficiência de mercado e falhas de mercado</h2>
<p>O objetivo deste capítulo foi desenvolver ferramentas para compreender como as firmas tomam decisões de produção e preços. Vimos o que os economistas entendem por custos e como eles variam conforme a quantidade produzida.</p>
<p>O que aprendemos? <span class="math display">\[ \boxed{CT=CF+CV} \]</span> <span class="math display">\[ \boxed{CMeT=CMeF+CMeV} \]</span> <span class="math display">\[ \boxed{CMg=\frac{\Delta CT}{\Delta Q}} \]</span></p>
<p>As curvas de custo, sozinhas, não determinam quanto uma firma produzirá. Para isso, precisaremos relacionar custos e receitas.</p>
<p>➡️ É exatamente o que faremos a seguir: usar essas ferramentas para entender as decisões de produção das firmas.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Conceito</th>
<th>Definição</th>
<th>Fórmula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Custos explícitos</strong></td>
<td>Exigem desembolso monetário pela firma</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Custos implícitos</strong></td>
<td>Não exigem desembolso, mas representam custos de oportunidade</td>
<td>—</td>
</tr>
<tr class="odd">
<td><strong>Custo fixo (CF)</strong></td>
<td>Não varia com a quantidade produzida</td>
<td><span class="math inline">\(CF\)</span></td>
</tr>
<tr class="even">
<td><strong>Custo variável (CV)</strong></td>
<td>Varia com a quantidade produzida</td>
<td><span class="math inline">\(CV\)</span></td>
</tr>
<tr class="odd">
<td><strong>Custo total (CT)</strong></td>
<td>Valor de todos os insumos utilizados na produção</td>
<td><span class="math inline">\(CT = CF + CV\)</span></td>
</tr>
<tr class="even">
<td><strong>Custo médio fixo (CMeF)</strong></td>
<td>Custo fixo por unidade produzida</td>
<td><span class="math inline">\(CMeF = \frac{CF}{Q}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Custo médio variável (CMeV)</strong></td>
<td>Custo variável por unidade produzida</td>
<td><span class="math inline">\(CMeV = \frac{CV}{Q}\)</span></td>
</tr>
<tr class="even">
<td><strong>Custo médio total (CMeT)</strong></td>
<td>Custo total por unidade produzida</td>
<td><span class="math inline">\(CMeT = \frac{CT}{Q}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Custo marginal (CMg)</strong></td>
<td>Aumento do custo decorrente de uma unidade adicional produzida</td>
<td><span class="math inline">\(CMg = \frac{\Delta CT}{\Delta Q}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Questões de Concurso</strong></p>
<p><strong>1. CEBRASPE — FUB — Economista — 2018</strong></p>
<p>Em um processo produtivo, se existir produto marginal decrescente em relação a um insumo, então os retornos de escala serão decrescentes.</p>
<p>( ) Certo ( ) Errado</p>
<p>Gabarito: Errado.</p>
<p>A lei dos rendimentos marginais decrescentes trata do curto prazo, mantendo pelo menos um fator fixo. Retornos de escala analisam o que ocorre quando todos os fatores variam, portanto são conceitos diferentes.</p>
<p><strong>2. CEBRASPE — TCE-RO — Auditor de Controle Externo/Economia — 2013</strong></p>
<p>Empresas com rendimentos marginais decrescentes terão os custos marginais aumentados à medida que o produto aumenta.</p>
<p>( ) Certo ( ) Errado</p>
<p>A questão consta da prova oficial do TCE-RO.</p>
<p>Gabarito: Certo.</p>
<p>É exatamente a relação que trabalhamos:</p>
<p><span class="math display">\[ PMg\downarrow\quad\Rightarrow\quad CMg\uparrow \]</span></p>
<p><strong>3. CEBRASPE — TCE-RO — Auditor de Controle Externo/Economia — 2013</strong></p>
<p>Segundo a lei do produto marginal decrescente, o produto marginal diminui à medida que se utiliza no longo prazo mais e mais dos fatores de produção envolvidos.</p>
<p>( ) Certo ( ) Errado</p>
<p>Gabarito: Errado.</p>
<p>A pegadinha está em “no longo prazo”. Produto marginal decrescente é analisado aumentando um fator enquanto os demais permanecem fixos.</p>
<p><strong>4. ESAF — CGU — Analista de Finanças e Controle — 2008</strong></p>
<p>Um projeto de investimento apresenta economias de escala quando:</p>
<ol type="A">
<li>o custo médio diminui quando a escala é reduzida.</li>
<li>o custo médio aumenta quando aumenta a utilização do fator variável.</li>
<li>o custo marginal aumenta quando aumenta a utilização do fator variável.</li>
<li>o custo total aumenta com o passar do tempo.</li>
<li>o custo médio diminui quando a escala do projeto é ampliada.</li>
</ol>
<p>Gabarito: E.</p>
<p><span class="math display">\[ \boxed{Q\uparrow\quad\text{e}\quad CMeT_{LP}\downarrow \Rightarrow \text{Economias de escala}} \]</span></p>
<p><strong>5. VUNESP — MPE-ES — Economista — 2013</strong></p>
<p>Economias de escala ocorrem quando a firma é capaz, por exemplo, de duplicar sua produção:</p>
<ol type="A">
<li>aumentando o custo médio na mesma proporção.</li>
<li>mais que dobrando seu custo total.</li>
<li>com crescimento de 150% em seu custo total.</li>
<li>reduzindo o custo médio.</li>
<li>com crescimento de 150% em seu custo médio.</li>
</ol>
<p>Gabarito: D.</p>
<p><a href="#/menu">← menu</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Aula 8_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Aula 8_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Aula 8_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Aula 8_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>